#!/bin/sh

# Cleanup previous build files and simulation outputs
rm -rf obj_dir
rm -f sigdelay.vcd

# Attach USB, if necessary (adjust the path as needed)
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# Run Verilator to translate Verilog into C++, including the testbench
verilator -Wall --cc --trace sigdelay.sv counter.sv ram2ports.sv --exe sigdelay_tb.cpp

# Build C++ project via make, automatically generated by Verilator
make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

# Run the executable simulation file
obj_dir/Vsigdelay

